---
version: "3"

services:
  iss_tracker-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: bobcode/iss_tracker_app:1.0
    container_name: iss_tracker_app
    ports:
      - "5000:5000"
    command: iss_tracker.py
